In [186]:
import pandas as pd
via = pd.read_excel("../pruebas_out_app/datos_via.xlsx")
bit = pd.read_excel("../pruebas_out_app/datos_bit.xlsx")
vacs = pd.read_excel("../pruebas_out_app/vacs.xlsx")

In [187]:
vacs

,Unnamed: 0,CONCESION,VAC,BIT,BASE,VIA,BASE-VAC,%BASE/VAC,%BIT/VAC,DECISION,ACCION
0,0,V5805,4866,4867.0,9007.0,7523.0,4141.0,1.851007,1.000206,VAC,Error en BASE
1,1,VAC-023,78993,80178.0,125254.0,72730.0,46261.0,1.585634,1.015001,VAC,No coincide nada
2,2,VAC-051,2929,NaN,NaN,NaN,NaN,NaN,NaN,VAC,Sin dato BASE
3,3,VAC-063,32620,NaN,NaN,NaN,NaN,NaN,NaN,VAC,Sin dato BASE
4,4,VAC-082,20986,18301.0,21165.0,NaN,179.0,1.008529,0.872058,VAC,No coincide nada
5,5,VAC-087,27341,NaN,NaN,NaN,NaN,NaN,NaN,VAC,Sin dato BASE
6,6,VAC-093,1095,NaN,NaN,NaN,NaN,NaN,NaN,VAC,Sin dato BASE
7,7,VAC-152,12435,NaN,NaN,NaN,NaN,NaN,NaN,VAC,Sin dato BASE
8,8,VAC-158,47945,NaN,NaN,NaN,NaN,NaN,NaN,VAC,Sin dato BASE
9,9,VAC-221,141,NaN,NaN,NaN,NaN,NaN,NaN,VAC,Sin dato BASE
10,10,VAC-226,1143,1160.0,1728.0,NaN,585.0,1.511811,1.014873,VAC,No coincide nada
11,11,VAC-231,53794,53997.0,53291.0,NaN,-503.0,0.990650,1.003774,VAC,Error en BASE
12,12,VAC-243,25701,25746.0,33919.0,25533.0,8218.0,1.319754,1.001751,VAC,Error en BASE
13,13,VAC-249,90,NaN,NaN,NaN,NaN,NaN,NaN,VAC,Sin dato BASE

In [185]:
decision_interurbanos = pd.read_excel("../pruebas_out_app/interurbanos_vcm_decision.xlsx")
vacs_decision = pd.read_excel("../pruebas_out_app/vacs_decision.xlsx")

In [79]:
decision_interurbanos.columns

Index(['CONCESION', 'VIA', 'BIT', 'BASE', 'BASE-VIA', 'BASE/VIA', 'BASE-BIT',
       '%BIT/BASE', '%BIT/VIA', 'DECISION', 'ACCION'],
      dtype='object')

In [22]:
finaldf = pd.DataFrame(columns=["Concesion","Fecha","Codtit","Validaciones","Coddes"])

In [55]:
bit.columns

Index(['Concesion', 'Periodo', 'Codtit', 'Subidos', 'Coddes'], dtype='object')

In [127]:
via

    Concesion      Fecha  Codtit  Validaciones  Coddes
0    URCM-005 2023-08-01    4101            48       0
1    URCM-005 2023-08-01    4102             3       0
2    URCM-005 2023-08-01    4103           174       0
3    URCM-005 2023-08-01    4104             2       0
4    URCM-005 2023-08-01    4110             4       0
..        ...        ...     ...           ...     ...
995  URCM-005 2023-08-02    4180            13       0
996  URCM-005 2023-08-02    4181           411       0
997  URCM-005 2023-08-02    4706           426       0
998  URCM-005 2023-08-02    8199             3       0
999  URCM-005 2023-08-02    8206             2       0

[1000 rows x 5 columns]

In [116]:
finaldf = pd.DataFrame(columns=["Concesion","Fecha","Codtit","Validaciones","Coddes"])
finaldf = via[via["Concesion"]=="URCM-005"]
decision_inter = decision_interurbanos[decision_interurbanos["CONCESION"]=="URCM-005"]
finaldf = pd.concat([finaldf, via[via["Concesion"]=="URCM-005"]], axis=0)
line = pd.DataFrame({"Concesion":"URCM-005", "Fecha":"", "Codtit":"Regulariza", "Validaciones":decision_inter["BASE-VIA"], "Coddes":"Regulariza"}, index=[0])
finaldf = pd.concat([finaldf, line], axis=0)
finaldf.Fecha = pd.to_datetime(finaldf.Fecha).dt.date
finaldf

# registro = via[via["Concesion"]=="URCM-005"]
# for i in registro.iterrows():
#     line = pd.DataFrame({"Concesion":i[1]["Concesion"], "Fecha":i[1]["Fecha"], "Codtit":i[1]["Codtit"], "Validaciones":i[1]["Validaciones"], "Coddes":i[1]["Coddes"]}, index=[0])
#     finaldf = pd.concat([finaldf, line], axis=0)
#     decision_inter = decision_interurbanos[decision_interurbanos["CONCESION"]==i[1]["Concesion"]]
#     line = pd.DataFrame({"Concesion":i[1]["Concesion"], "Fecha":i[1]["Fecha"], "Codtit":"Regulariza", "Validaciones":decision_inter["BASE-VIA"], "Coddes":"Regulariza"}, index=[0])
#     finaldf = pd.concat([finaldf, line], axis=0)
# finaldf

    Concesion       Fecha      Codtit  Validaciones      Coddes
0    URCM-005  2023-08-01        4101          48.0           0
1    URCM-005  2023-08-01        4102           3.0           0
2    URCM-005  2023-08-01        4103         174.0           0
3    URCM-005  2023-08-01        4104           2.0           0
4    URCM-005  2023-08-01        4110           4.0           0
..        ...         ...         ...           ...         ...
996  URCM-005  2023-08-02        4181         411.0           0
997  URCM-005  2023-08-02        4706         426.0           0
998  URCM-005  2023-08-02        8199           3.0           0
999  URCM-005  2023-08-02        8206           2.0           0
0    URCM-005         NaT  Regulariza      622687.0  Regulariza

[2001 rows x 5 columns]

In [130]:
bit.columns

Index(['Concesion', 'Fecha', 'Codtit', 'Subidos', 'Coddes'], dtype='object')

In [ ]:
finaldf = pd.DataFrame(columns=["Concesion","Fecha","Codtit","Validaciones","Coddes"])
finaldf = bit[bit["Concesion"]=="URCM-005"]
decision_inter = decision_interurbanos[decision_interurbanos["CONCESION"]=="URCM-005"]
finaldf = pd.concat([finaldf, via[via["Concesion"]=="URCM-005"]], axis=0)
line = pd.DataFrame({"Concesion":"URCM-005", "Fecha":"", "Codtit":"Regulariza", "Validaciones":decision_inter["BASE-VIA"], "Coddes":"Regulariza"}, index=[0])
finaldf = pd.concat([finaldf, line], axis=0)
finaldf.Fecha = pd.to_datetime(finaldf.Fecha).dt.date
finaldf

In [ ]:
import math
finaldf = pd.DataFrame(columns=["Concesion","Fecha","Codtit","Coddes","Validaciones"])
for registro in vacs_decision.iterrows():
    registro = registro[1]
    if registro["DECISION"] == "VAC":
        finaldf = pd.concat([finaldf, vacs[vacs["Concesion"]==registro["CONCESION"]]], axis=0)
        finaldf.Fecha = pd.to_datetime(finaldf.Fecha, format="mixed").dt.strftime("%d/%m/%Y")
    elif registro["DECISION"] == "VAC+Reg. Base":
        new_df = pd.DataFrame(columns=["Concesion","Fecha","Codtit","Validaciones","Coddes"])
        new_df = vacs[vacs["Concesion"]==registro["CONCESION"]]
        decision_inter = vacs_decision[vacs_decision["CONCESION"]==registro["CONCESION"]]
        new_df = pd.concat([new_df, vacs[vacs["Concesion"]==registro["CONCESION"]]], axis=0)
        new_df.Fecha = pd.to_datetime(new_df.Fecha).dt.strftime("%d/%m/%Y")
        line = pd.DataFrame({"Concesion":registro["CONCESION"], "Fecha":vacs["Fecha"].dt.strftime("%m/%Y"), "Codtit":"Regulariza", "Validaciones":decision_inter["BASE-VIA"], "Coddes":"Regulariza"}, index=[0])
        new_df = pd.concat([new_df, line], axis=0)
        finaldf = pd.concat([finaldf, new_df], axis=0)
finaldf

In [177]:
finaldf = pd.DataFrame(columns=["Concesion","Fecha","Codtit","Coddes","Validaciones"])
via["Fecha"] = pd.to_datetime(via["Fecha"])
for registro in decision_interurbanos.iterrows():
    registro = registro[1]
    if registro["DECISION"] == "VIA":
        finaldf = pd.concat([finaldf, via[via["Concesion"]==registro["CONCESION"]]], axis=0)
        finaldf.Fecha = pd.to_datetime(finaldf.Fecha, format="mixed").dt.strftime("%d/%m/%Y")
    elif registro["DECISION"] == "BIT":
        bit.rename(columns={"Periodo":"Fecha","Subidos":"Validaciones"}, inplace=True, errors="ignore")
        finaldf = pd.concat([finaldf, bit[bit["Concesion"]==registro["CONCESION"]]], axis=0)
        finaldf.Fecha = pd.to_datetime(finaldf.Fecha, format="mixed").dt.strftime("%d/%m/%Y")
    elif registro["DECISION"] == "VIA+Reg. Base":
        new_df = pd.DataFrame(columns=["Concesion","Fecha","Codtit","Validaciones","Coddes"])
        new_df = via[via["Concesion"]==registro["CONCESION"]]
        decision_inter = decision_interurbanos[decision_interurbanos["CONCESION"]==registro["CONCESION"]]
        new_df = pd.concat([new_df, via[via["Concesion"]==registro["CONCESION"]]], axis=0)
        new_df.Fecha = pd.to_datetime(new_df.Fecha).dt.strftime("%d/%m/%Y")
        line = pd.DataFrame({"Concesion":registro["CONCESION"], "Fecha":via["Fecha"].dt.strftime("%m/%Y"), "Codtit":"Regulariza", "Validaciones":decision_inter["BASE-VIA"], "Coddes":"Regulariza"}, index=[0])
        new_df = pd.concat([new_df, line], axis=0)
        finaldf = pd.concat([finaldf, new_df], axis=0)
    elif registro["DECISION"] == "BIT+Reg. Base":
        bit.rename(columns={"Periodo":"Fecha","Subidos":"Validaciones"}, inplace=True, errors="ignore")
        new_df = pd.DataFrame(columns=["Concesion","Fecha","Codtit","Validaciones","Coddes"])
        new_df = bit[bit["Concesion"]==registro["CONCESION"]]
        decision_inter = decision_interurbanos[decision_interurbanos["CONCESION"]==registro["CONCESION"]]
        new_df = pd.concat([new_df, bit[bit["Concesion"]==registro["CONCESION"]]], axis=0)
        new_df.Fecha = pd.to_datetime(new_df.Fecha).dt.strftime("%d/%m/%Y")
        line = pd.DataFrame({"Concesion":registro["CONCESION"], "Fecha":bit["Fecha"].dt.strftime("%m/%Y"), "Codtit":"Regulariza", "Validaciones":decision_inter["BASE-VIA"], "Coddes":"Regulariza"}, index=[0])
        new_df = pd.concat([new_df, line], axis=0)
        finaldf = pd.concat([finaldf, new_df], axis=0)
finaldf

C:\Users\ray\AppData\Local\Temp\ipykernel_8108\1323944038.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  finaldf = pd.concat([finaldf, via[via["Concesion"]==registro["CONCESION"]]], axis=0)

       Concesion       Fecha      Codtit      Coddes Validaciones
0       URCM-005  01/08/2023        4101           0           48
1       URCM-005  01/08/2023        4102           0            3
2       URCM-005  01/08/2023        4103           0          174
3       URCM-005  01/08/2023        4104           0            2
4       URCM-005  01/08/2023        4110           0            4
...          ...         ...         ...         ...          ...
683817   VCM-702  31/08/2023        4181           0          4.0
683818   VCM-702  31/08/2023        4706           0          5.0
683819   VCM-702  31/08/2023        8214           0          5.0
683820   VCM-702  31/08/2023        9490           0          2.0
0        VCM-702     08/2023  Regulariza  Regulariza          NaN

[718213 rows x 5 columns]

In [154]:
finaldf = pd.DataFrame(columns=["Concesion","Fecha","Codtit","Coddes"])
finaldf = pd.concat([finaldf, bit[bit["Concesion"]=="URCM-005"]], axis=0)
bit.rename(columns={"Periodo":"Fecha","Subidos":"Validaciones"}, inplace=True, errors="ignore")
finaldf = pd.concat([finaldf, bit[bit["Concesion"]=="URCM-005"]], axis=0)
line = pd.DataFrame({"Concesion":registro["CONCESION"], "Fecha":bit["Fecha"], "Codtit":"Regulariza", "Validaciones":decision_inter["BASE-VIA"], "Coddes":"Regulariza"}, index=[0])
new_df = pd.concat([new_df, line], axis=0)
finaldf = pd.concat([finaldf, new_df], axis=0)
finaldf

       Concesion                Fecha      Codtit      Coddes  Validaciones
57      URCM-005              2023-08        4136         NaN        5501.0
58      URCM-005              2023-08        4103         NaN       92271.0
59      URCM-005              2023-08        4147         NaN         379.0
60      URCM-005              2023-08        4112         NaN         369.0
61      URCM-005              2023-08        4137         NaN        1227.0
...          ...                  ...         ...         ...           ...
683818   VCM-702  2023-08-31 00:00:00        4706           0           5.0
683819   VCM-702  2023-08-31 00:00:00        8214           0           5.0
683820   VCM-702  2023-08-31 00:00:00        9490           0           2.0
0        VCM-702                 2023  Regulariza  Regulariza           NaN
0          U0058              2023-08  Regulariza  Regulariza           NaN

[59668 rows x 5 columns]